import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Explore NEXT14 APP Directory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  slides,
}: Readonly<{
  children: React.ReactNode;
  slides: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-tiles bg-fixed inset-0 absolute z-[-1]" />

        {children}
        {slides}

        <footer className="min-h-16 px-8 flex items-center justify-between border-t border-white/10 bg-neutral-950">
          <p>Initialized with NEXT14 APP Directory 🚀</p>
          <a href="https://github.com/Farrely-F">Farrely-F &copy; 2024</a>
        </footer>
      </body>
    </html>
  );
}
