import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Intercepting Routes",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <div>{children}</div>
    </div>
  );
}
